### ISSUE TITLE
[🐛BUG]wcf.get_self_wxid()获取到的为当前微信号，与WxMsg里不一致

### ISSUE THREAD

**Issue by tudou2021** [lich0821/WeChatRobot#10]
**描述这个 bug**
对 bug 作一个清晰简明的描述。

**使用环境（请补全下列信息）：**
- 操作系统： Windows 7 
- 操作系统版本： 32 位  
- Python 版本 3.8.9
 
当别人艾特尔我的时候
wcf.get_self_wxid()获取到的为当前微信号
而wcf_pb2.WxMsg里获取到的sender=我之前的微信号

**Comment by lich0821** [comment]
是机器人号通过手机往群里发消息？提供一下复现方法。
