### ISSUE TITLE
[🐛BUG] 用一句话描述您的问题。

### ISSUE THREAD

**Issue by jjyyfff** [lich0821/WeChatRobot#12]
**描述这个 bug**
对 bug 作一个清晰简明的描述。

**使用环境（请补全下列信息）：**
- 操作系统：【如 Windows 7, Windows 10, Windows Server 2008 等】
- 操作系统版本：[32 位 或 64 位】
- Python 版本 【如 3.7.9 32位, 3.8.15 64位 等】

**屏幕截图**
添加屏幕截图以帮助解释您的问题。（可选）

**崩溃信息**
微信崩溃原因描述文件内容。（可选）

想进群学习，老兄。

**Comment by lich0821** [comment]
被你这个BUG吓着了🤣
项目首页能看到二维码。
