### ISSUE TITLE
能拿到微信客户端的二维码图片吗

### ISSUE THREAD

**Issue by shashiyu** [lich0821/WeChatRobot#13]
感谢作者提供如此优秀的工具，请问能拿到微信客户端的二维码图片吗，还有能解密OpenIMContact.db吗，企业微信来的消息或人员获取还有点问题

**Comment by lich0821** [comment]
有用就好！
1. 是指登录二维码吗？
2. 这个数据库之前没研究过，得有时间了看看才知道

**Comment by lich0821** [comment]
还有这需求的话可以提到 [WeChatFerry](https://github.com/lich0821/WeChatFerry)。
