### ISSUE TITLE
关于chatgpt

### ISSUE THREAD

**Issue by like-tbmost** [lich0821/WeChatRobot#18]
如果我想接入chatgpt，该如何去抓取我账号里的那些参数
可不可以直接用本地的电脑开启v2使用国外的代理，然后不填proxy的参数啊

**Comment by like-tbmost** [comment]
![3ada039de08bae8bb50fd9df4eb7656](https://github.com/lich0821/WeChatRobot/assets/93694054/90399059-a6b5-4c64-9916-660369fd232e)

**Comment by lich0821** [comment]
没理解你的问题。你现在是遇到了什么困难吗？

**Comment by like-tbmost** [comment]
既然可以接入讯飞星火大模型，那chatgpt应该也行吧，我看都有例子的，我想问一下，如何去抓取我chatgpt的这些参数，没有头绪

**Comment by lich0821** [comment]
不用抓取，直接填key就可以了。具体看配置文件。

**Comment by like-tbmost** [comment]
好像没有chatgpt的教程😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月12日(周日) 晚上11:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lich0821/WeChatRobot] 关于chatgpt (Issue #18)




 
不用抓取，直接填key就可以了。具体看配置文件。

**Comment by like-tbmost** [comment]
OK了，感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月12日(周日) 晚上11:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lich0821/WeChatRobot] 关于chatgpt (Issue #18)




 
不用抓取，直接填key就可以了。具体看配置文件。
