### ISSUE TITLE
chatglm3 代码模式生成了爱心图片，但不能发送到微信

### ISSUE THREAD

**Issue by JosenJin** [lich0821/WeChatRobot#24]
chatglm3代码模式，生成了爱心，但结果图片没有发送到微信，只提示：这就是一个爱心形状的图形。希望你会喜欢！如果你有其他要求或需要进一步的调整，请告诉我。

这是为什么？我看了目录也生成了照片，就是没有回复到微信中。

请大神指点。

**Comment by lich0821** [comment]
**描述这个 bug**
对 bug 作一个清晰简明的描述：
* 要实现什么目的？
* 怎么做的？
* 遇到什么问题？

**使用环境（请补全下列信息）：**
- 操作系统：【如 Windows 7, Windows 10, Windows Server 2008 等】
- 操作系统版本：[32 位 或 64 位】
- Python 版本 【如 3.7.9 32位, 3.8.15 64位 等】

**屏幕截图**
添加屏幕截图以帮助解释您的问题。（可选）

**崩溃信息**
微信崩溃原因描述文件内容。（可选）
