### ISSUE TITLE
更新open ai软件包

### ISSUE THREAD

**Issue by xumouren1234** [lich0821/WeChatRobot#30]
旧版open ai软件包不能
连接图片制作

**Comment by 165056821** [comment]
我也遇到同样的需求。谢谢。

**Comment by lich0821** [comment]
#45

**Comment by lich0821** [comment]
[Upgrade openai](https://github.com/lich0821/WeChatRobot/commit/27277c97d235b84c6354c21ab80285bd0d3f30fa)
