### ISSUE TITLE
在ubuntu环境下运行出现错误

### ISSUE THREAD

**Issue by 1823616178** [lich0821/WeChatRobot#43]
Linux环境1 wsl ubuntu 22.04 
Linux环境2  ubuntu 22.04 物理机
python版本 3.10.6

windows环境 windows11 
python版本 3.10.7

Win环境下运行正常

Linux环境下报错：

![3d6193f1fdf811d8e2ee4a63adc092b](https://github.com/lich0821/WeChatRobot/assets/24314110/81a8bffc-c96b-4714-a8c2-50571d5f9593)

经测试，在WSL和物理机Linux 下报一样的错误，WIN下正常

**Comment by lich0821** [comment]
这个还是关掉吧。简单来说，只支持`Windows`。
