### ISSUE TITLE
如何指定ChatGPT的Model？

### ISSUE THREAD

**Issue by KloseYao** [lich0821/WeChatRobot#45]
例如我希望使用3.5-turbo-16k，或者gpt4的接口，但是默认他调用的模型太老了，数据仅停留在2020年

**Comment by Mr-hello** [comment]
进入根目录的base文件夹，修改func_chatgpt文件就可以了

**Comment by lich0821** [comment]
[Upgrade openai](https://github.com/lich0821/WeChatRobot/commit/27277c97d235b84c6354c21ab80285bd0d3f30fa)
