### ISSUE TITLE
macOS python安装环境后提示缺少wcferry\wcf.exe文件

### ISSUE THREAD

**Issue by FFFhao** [lich0821/WeChatRobot#46]
这个项目只支持windows系统吗？

**Comment by hotdogarea** [comment]
我也遇到同样的问题，mac上不能部署吗
<img width="771" alt="image" src="https://github.com/lich0821/WeChatRobot/assets/11146882/38eef8de-f42b-4bd8-99b3-1062baddb679">

**Comment by lich0821** [comment]
请看[`FAQ`](https://mp.weixin.qq.com/s/bdPNrbJYoXhezCzHMqLoEw)
