### ISSUE TITLE
请问有工作日定时提醒发送消息的功能吗？

### ISSUE THREAD

**Issue by BTSRK** [lich0821/WeChatRobot#48]
工作日定时发送自定义消息的功能。
还有请问下，为什么天气预报功能不能正常使用（时间不对），是因为我接入的是chatgpt3.5吗？  如果要正常使用是不是需要接入chatgpt4.0？

**Comment by lich0821** [comment]
具体业务自己写就好了，这只是个示例，参考用的。
天气预报用相应的服务接口比用大模型靠谱得多。
