### ISSUE TITLE
[💡SUG] 提允许通过配置特定的wxid来自动屏蔽或忽视来自这些wxid的对话请求，以减少不必要的干扰。

### ISSUE THREAD

**Issue by samni728** [lich0821/WeChatRobot#50]
问题背景： 在管理用户请求的系统中，某些用户可能因为各种原因需要被临时或永久屏蔽对话请求。比如，滥用服务、发送垃圾信息等行为。目前，系统缺乏直接通过用户的微信ID来快速屏蔽对话请求的功能。

期望的解决方案： 实现一个功能，让管理员或系统维护者能通过添加用户的微信ID到一个黑名单中，来自动屏蔽或忽略这些用户的对话请求。这个功能应该包括：

一个界面或命令行工具，用于输入需要屏蔽的用户wxid。
一个黑名单数据库或列表，存储被屏蔽用户的wxid。
一个逻辑判断机制，在接收到用户请求时检查其wxid是否在黑名单中。
如果用户的wxid在黑名单中，则自动忽略或拒绝其对话请求，可能伴随一条通知消息告知用户。
考虑的替代方案：

基于用户行为的自动屏蔽： 系统根据用户的行为自动判断是否需要屏蔽，如发送消息频率、内容质量等指标。
举报机制： 允许其他用户举报不当行为，当举报达到一定数量时自动触发屏蔽逻辑。
时间限制屏蔽： 不是永久屏蔽用户wxid，而是给予一定时间的禁言或屏蔽，过后自动解除。

**Comment by lich0821** [comment]
这个功能听着挺有意思，不过，机器人不处理，已经就是“屏蔽”了吧？

**Comment by Jeff-Hugh** [comment]
> 这个功能听着挺有意思，不过，机器人不处理，已经就是“屏蔽”了吧？

请问如何设置机器人不处理某用户的消息呢？

**Comment by lich0821** [comment]
> > 这个功能听着挺有意思，不过，机器人不处理，已经就是“屏蔽”了吧？
> 
> 请问如何设置机器人不处理某用户的消息呢？

😂啥也不做，就是不处理
