### ISSUE TITLE
[🐛BUG] 配置 bard 响应超时。

### ISSUE THREAD

**Issue by sozcos** [lich0821/WeChatRobot#51]
**配置 bard 之后, 报超时error, 已开启vpn, 网页端 Gemini 可用**

**使用环境（请补全下列信息）：**
- 操作系统：Windows 11 22621.3155
- 操作系统版本：【64 位】
- Python 版本 【Python 3.12.1 64 位 】

**屏幕截图**

![image](https://github.com/lich0821/WeChatRobot/assets/87360050/18f24597-1f54-45da-87ee-e04ec0ba2d10)
![image](https://github.com/lich0821/WeChatRobot/assets/87360050/a6b51438-ffed-4586-842c-e2c9eaeb17e0)

**Comment by lich0821** [comment]
凭提供信息无法复现。
