### ISSUE TITLE
[🐛BUG] Google Gemini模型没有正确识别提示词来运行

### ISSUE THREAD

**Issue by SDCOM-0415** [lich0821/WeChatRobot#53]
**描述这个 bug**
对 bug 作一个清晰简明的描述：
这个bug来自于Google Gemini模型，它并没有正确的识别到提示词，它认为“我是 Gemini，是 Google 开发的多模态 AI 语言模型。”
我在提示词的地方正确设置了，可是它似乎没有正确的生效？
具体可以查看屏幕截图
如果需要作者可以联系我sdcom@sdcom.asia
</p>

**使用环境（请补全下列信息）：**
- 操作系统：Windows Server 2012R2【如 Windows 7, Windows 10, Windows Server 2008 等】
- 操作系统版本：64 位【32 位或 64 位】
- Python 版本：3.10.11【如 3.7.9 32 位，3.8.15 64 位 等】

**屏幕截图**
添加屏幕截图以帮助解释您的问题。（可选）
![image](https://github.com/lich0821/WeChatRobot/assets/127208666/c39d0c38-3608-4133-a258-8628c8bbf8b6)
![image](https://github.com/lich0821/WeChatRobot/assets/127208666/41ea18c1-39c7-4456-a6d5-f2c6da92b2c1)
![image](https://github.com/lich0821/WeChatRobot/assets/127208666/a3b611fa-d068-4e2e-a670-da6adf97c347)

**Comment by lich0821** [comment]
这个BUG可能提给Google比较合适。看看有没有大佬支招。

**Comment by SDCOM-0415** [comment]
很显然我找不到提交方式

**Comment by lich0821** [comment]
> 很显然我找不到提交方式

哈哈哈哈，这是 [Gemini 的 Python 客户端](https://github.com/google/generative-ai-python)
