### ISSUE TITLE
LoadLibrary 调用失败

### ISSUE THREAD

**Issue by Xiao-Fangff** [lich0821/WeChatRobot#57]
![image](https://github.com/lich0821/WeChatRobot/assets/92212954/2909e092-088f-429d-ad9d-ff363afab18d)
我在运行 `python main.py` 时遇到以上报错，请问怎么解决？

**Comment by lich0821** [comment]
[🙋 FAQ](https://mp.weixin.qq.com/s/bdPNrbJYoXhezCzHMqLoEw) Q16，注意版本。

**Comment by Xiao-Fangff** [comment]
> [🙋 FAQ](https://mp.weixin.qq.com/s/bdPNrbJYoXhezCzHMqLoEw) Q16，注意版本。

成功了，谢谢帮助！
