### ISSUE TITLE
[🐛BUG] go版本调用/ai ,程序报错闪退

### ISSUE THREAD

**Issue by anranatt** [lich0821/WeChatRobot#59]
**描述这个 bug**
对 bug 作一个清晰简明的描述：
- 想做什么？
接入ai聊天到微信群
- 现在怎么做？
- 遇到什么问题？

**使用环境（请补全下列信息）：**
- 操作系统：win11
- 操作系统版本：【 64 位】

**屏幕截图**
![c2b9bc0af7589b2e779a77559f3ee3d](https://github.com/lich0821/WeChatRobot/assets/18742324/af07cc86-c767-4975-9cd6-2f4a981a2bbe)

**Comment by lich0821** [comment]
提错地方了，提到这里：[Wrest Chat](https://github.com/opentdp/wrest-chat)
