### ISSUE TITLE
运行python main.py时提示连接失败

### ISSUE THREAD

**Issue by KwdeTfpv** [lich0821/WeChatRobot#62]
**描述这个 bug**
对 bug 作一个清晰简明的描述：运行python main.py时提示连接失败
- 想做什么？
- 现在怎么做？
- 遇到什么问题？
**微信版本：**
   3.9.2.23
**wcf.txt**
[2024-05-29 14:15:00.744] [debug] [WCF] [log.cpp::33::InitLogger] InitLogger with debug level
[2024-05-29 14:15:00.745] [error] [WCF] [spy.cpp::27::InitSpy] 获取微信版本失败

**python main.py**
2024-05-29 14:14:58 wcferry version: 39.0.14.1
2024-05-29 14:15:02 连接失败: Connection refused

**使用环境（请补全下列信息）：**
- 操作系统：【Windows 10】
- 操作系统版本：【64 位】
- Python 版本 【3.11 64位】

**屏幕截图**
添加屏幕截图以帮助解释您的问题。（可选）

**Comment by lich0821** [comment]
微信版本？

**Comment by lich0821** [comment]
确认一下微信版本。

**Comment by KwdeTfpv** [comment]
> 确认一下微信版本。

![image](https://github.com/lich0821/WeChatRobot/assets/91249019/43d10c43-cc99-4460-8fa5-f9e1c5d46684)

**Comment by KwdeTfpv** [comment]
**wx_error.log**

2024-05-29 15:26:59,679 WCF ERROR client.py::__init__[92]:连接失败: Connection refused

**Comment by KwdeTfpv** [comment]
我是从高版本替换成低版本的，是否可能跟这个有关，谢谢！

**Comment by lich0821** [comment]
> **wx_error.log**
> 
> 2024-05-29 15:26:59,679 WCF ERROR client.py::**init**[92]:连接失败: Connection refused

这个只是说明“服务端”没有起来，判断不了原因。

**Comment by lich0821** [comment]
> 微信版本 我是从高版本覆盖安装成低版本的，是否可能跟这个有关，谢谢！

倒是有可能。那个错误，最大的可能是是非32位的版本，导致获取不到版本信息。

**Comment by KwdeTfpv** [comment]
> > 微信版本 我是从高版本覆盖安装成低版本的，是否可能跟这个有关，谢谢！
> 
> 倒是有可能。那个错误，最大的可能是是非32位的版本，导致获取不到版本信息。

我是在[Releases](https://github.com/lich0821/WeChatRobot/releases) [v39.0.14.0](https://github.com/lich0821/WeChatRobot/releases/tag/v39.0.14.0) 下的版本，查了issue发现没有人遇到这种问题，也问了一下使用过的人也没有遇到过，难受

**Comment by KwdeTfpv** [comment]
已经解决，把微信装到别的目录。不要覆盖原来的目录就可以了，谢谢！
