### ISSUE TITLE
如果只想针对某一个群发送信息应该怎么操作啊[🐛BUG] 用一句话描述您的问题。

### ISSUE THREAD

**Issue by jwc19890114** [lich0821/WeChatRobot#63]
如果只想针对某一个群发送信息应该怎么操作啊，应该怎么只对特定群的消息进行处理呢

**Comment by lich0821** [comment]
## [Quick Start](https://github.com/lich0821/WeChatRobot?tab=readme-ov-file#quick-start)
0. 遇到问题先看看上面的**文档、教程和 FAQ。**
    - 按照步骤来，版本保持一致，少走弯路。
    - 按照步骤来，版本保持一致，少走弯路。
    - 按照步骤来，版本保持一致，少走弯路。
