### ISSUE TITLE
发送中文名图片失败

### ISSUE THREAD

**Issue by GaoZhuoXiu** [lich0821/WeChatRobot#68]
func: FUNC_SEND_IMG
file {
  path: "E:\\wechatRobot\\你好.png"
  receiver: "filehelper"
}

英文图片能直接发送，但中文的不行，rsp.status为-2，如何解决

**Comment by GaoZhuoXiu** [comment]
E:\\wechatRobot\\你好.png

**Comment by lich0821** [comment]
[发送中文文件的时候发送失败](https://github.com/lich0821/WeChatFerry/issues/140)

**Comment by GaoZhuoXiu** [comment]
> [发送中文文件的时候发送失败](https://github.com/lich0821/WeChatFerry/issues/140)

感谢，改成全局UTF-8解决了
