### ISSUE TITLE
发生未知错误：'ascii' codec can't encode characters in position 60-62: ordinal not in range(128)

### ISSUE THREAD

**Issue by Liumy2233** [lich0821/WeChatRobot#69]
按照正常流程设置的，不知道为什么会这样

报错是：
发生未知错误：'ascii' codec can't encode characters in position 60-62: ordinal not in range(128)
无法从 ChatGPT 获得答案

- 操作系统：Windows 10
- 操作系统版本：64 位】
- Python 版本 3.12
求大佬指点

**Comment by lich0821** [comment]
1、这不是BUG。
2、这种问题，来提ISSUE不如直接问ChatGPT或者百度来得快。
3、解决方法：设置一下字符集，具体操作步骤可以问AI或者百度。

**Comment by Liumy2233** [comment]
好的，不好意思打扰到你了，感谢提醒
