### ISSUE TITLE
[🐛BUG] 群里拷贝@消息修改后发送，msg.is_at(self.wxid)接口识别为非群@消息。

### ISSUE THREAD

**Issue by HappyHoneybadger** [lich0821/WeChatRobot#7]
**描述这个 bug**
对 bug 作一个清晰简明的描述。
群里直接拷贝@消息后发送，processMsg函数中调用msg.is_at(self.wxid)接口识别为非群@消息。
**使用环境（请补全下列信息）：**
- 操作系统：【如 Windows 7, Windows 10, Windows Server 2008 等】
- 操作系统版本：[32 位 或 64 位】
- Python 版本 【如 3.7.9 32位, 3.8.15 64位 等】

**屏幕截图**
添加屏幕截图以帮助解释您的问题。（可选）

**崩溃信息**
微信崩溃原因描述文件内容。（可选）

**Comment by lich0821** [comment]
@腾讯

**Comment by Xiaeer** [comment]
这是腾讯的"bug“，复制@消息，不算@消息
