### ISSUE TITLE
[🐛BUG] get_info_by_wxid方法无效

### ISSUE THREAD

**Issue by onlyWYY** [lich0821/WeChatRobot#71]
**描述这个 bug**
对 bug 作一个清晰简明的描述：
- 想通过这个方法获取好友的详细信息，但是各种情况都是返回空。，请问是否该方法已经停止使用或者维护了呢？

**使用环境：**
- 操作系统： Windows 11
- 操作系统版本： 64 位
- Python 版本 【如 3.7.9 32 位，3.8.15 64 位 等】

**屏幕截图**
添加屏幕截图以帮助解释您的问题。（可选）
![screenshot-20240812-110807](https://github.com/user-attachments/assets/8b663e4c-8db1-4e70-9e21-6eff04c87ad1)

**Comment by lich0821** [comment]
[[🐛BUG] 测试了几个版本，get_info_by_wxid 都返回空数据](https://github.com/lich0821/WeChatFerry/issues/204)
