### ISSUE TITLE
[🐛BUG] 智普api不起作用

### ISSUE THREAD

**Issue by CJSen** [lich0821/WeChatRobot#75]
**描述这个 bug**
对 bug 作一个清晰简明的描述：
智普api不起作用
python main.py -c 6
查看代码。。。漏了“, ChatType.ZhiPu.value”，具体看截图

**使用环境（请补全下列信息）：**
- 操作系统：Windows Server 2016
- 操作系统版本：64 位
- Python 版本 3.10

**屏幕截图**
![image](https://github.com/user-attachments/assets/6b939622-b11c-491a-8ace-e9b626bb76b9)

**Comment by lich0821** [comment]
哈哈哈哈，来个 PR

**Comment by CJSen** [comment]
> 哈哈哈哈，来个 PR

正在跑，issue提早了哈哈。。。没跑起来，还有些bug。一会跑起来了一起提
