### ISSUE TITLE
[🐛BUG] 初始化失败！

### ISSUE THREAD

**Issue by NC-Cj** [lich0821/WeChatRobot#78]
- 按照步骤使用 wcferry version: 39.2.4.0 ，运行主程序直接报错: 初始化失败！
- 操作系统： Windows 11
- 操作系统版本： 64 位
- Python 版本:  3.11.3

**屏幕截图**
![image](https://github.com/user-attachments/assets/250b522e-132f-4bca-af1e-60b399d06592)

**Comment by lich0821** [comment]
无法复现。
