### ISSUE TITLE
[🐛BUG] 被微信封号的概率有多高

### ISSUE THREAD

**Issue by liuguangrui123** [lich0821/WeChatRobot#8]
**描述这个 bug**
对 bug 作一个清晰简明的描述。

**使用环境（请补全下列信息）：**
- 操作系统：【如 Windows 7, Windows 10, Windows Server 2008 等】
- 操作系统版本：[32 位 或 64 位】
- Python 版本 【如 3.7.9 32位, 3.8.15 64位 等】

**屏幕截图**
添加屏幕截图以帮助解释您的问题。（可选）

**崩溃信息**
微信崩溃原因描述文件内容。（可选）

**Comment by lich0821** [comment]
这问题，可能得微信来回答了 @腾讯
目前看到的，除了
* 刚注册小号马上用；
* 用超人手速发消息；
* 短时间被多个群聊踢出来（估计是被举报了）

还没听说有被封的。
