### ISSUE TITLE
无法自动通过好友申请

### ISSUE THREAD

**Issue by px-poxiao** [lich0821/WeChatRobot#81]
如题
后台可以正常接受到好友申请消息但无任何动作，包括通过好友申请或向wx_error.log内发送错误信息
不过手动通过后可以正常发送“Hi {用户名}，我自动通过了你的好友请求。”

**使用环境：**
- 操作系统：Windows Server 2022 数据中心版
- 操作系统版本：64位
- Python 版本  3.10.11

<img width="960" alt="image" src="https://github.com/user-attachments/assets/98e19745-7e72-4577-9689-bb7fb4432962">

**Comment by lich0821** [comment]
https://github.com/lich0821/WeChatFerry/issues/196#issuecomment-2269332651
