### ISSUE TITLE
[🐛BUG]  Failed opening file C:Projs\WeChatRobotllogslwcf.txt for writing: no such file or directory,   Windows Server 2012R2, 64 , python3.10.0

### ISSUE THREAD

**Issue by SunZhiHuanDaGe** [lich0821/WeChatRobot#84]
**描述这个 bug**
对 bug 作一个清晰简明的描述：
- 想做什么？
- 现在怎么做？
- 遇到什么问题？

**使用环境（请补全下列信息）：**
- 操作系统：【如 Windows 7, Windows 10, Windows Server 2008 等】
- 操作系统版本：【32 位或 64 位】
- Python 版本 【如 3.7.9 32 位，3.8.15 64 位 等】

**屏幕截图**
![00685da4030746c1a927d6d461424095](https://github.com/user-attachments/assets/9715fd9b-d3b7-4073-b0bc-62f87809608a)

**Comment by lich0821** [comment]
Closing this as a duplicate of  #70
