### ISSUE TITLE
[🐛BUG] 获取登录二维码出错

### ISSUE THREAD

**Issue by ivanwong23** [lich0821/WeChatRobot#86]
调用方法：get_qrcode()
错误：Call FUNC_REFRESH_QRCODE failed: Exiting... Error parsing message with type 'wcf.Response'

wcferry version: 39.2.4.0

**Comment by lich0821** [comment]
参见版本 [功能](https://github.com/lich0821/WeChatFerry/issues/185#issuecomment-2223051748)
